/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;
import static Interfaces.Ventana1.getMiGrafo;

/**
 *
 * @author G. Angelo, S. Estefania y S. Jose
 */
public class Aviso extends javax.swing.JFrame {

    /**
     * Constructor de la clase Aviso. Inicializa la interfaz gráfica.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @version: 27/10/2023
     */
    public Aviso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Mensaje = new javax.swing.JLabel();
        AceptarM = new javax.swing.JButton();
        CancelarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(550, 310));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mensaje.setText("Al cargar un nuevo archivo, los datos de la ejecución actual se eliminarán de forma permanente");
        jPanel1.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        AceptarM.setText("Aceptar");
        AceptarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarMActionPerformed(evt);
            }
        });
        jPanel1.add(AceptarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        CancelarM.setText("Cancelar");
        CancelarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarMActionPerformed(evt);
            }
        });
        jPanel1.add(CancelarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que permite cancelar la interaccion del usuario y regresar a la
     * ventana anterior.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     * @version: 27/10/2023
     */
    private void CancelarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarMActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarMActionPerformed

    /**
     * Manejador de eventos para el botón "Aceptar". Cierra la ventana actual,
     * abre un archivo, crea un nuevo grafo y lo llena con datos desde el
     * archivo.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     */
    private void AceptarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarMActionPerformed
        this.dispose();
        Ventana1.getFunc().abrir_archivo();
        Grafo NuevoGrafo = new Grafo();
        Ventana1.miGrafo= NuevoGrafo;        
        Ventana1.getMiGrafo().llenar_grafo();
        
    }//GEN-LAST:event_AceptarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aviso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarM;
    private javax.swing.JButton CancelarM;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
