/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Extras.Funciones;

/**
 *
 * @author joses
 */
public class ConectarUsuarios extends javax.swing.JFrame {

    public Funciones func;

    /**
     * Creates new form Ventana3
     */
    public ConectarUsuarios() {
        initComponents();
        func = new Funciones();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloCU = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CancelarCU = new javax.swing.JButton();
        AceptarCU = new javax.swing.JButton();
        Nombre1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloCU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloCU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCU.setText("Conectar Usuarios");
        jPanel1.add(TituloCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, 40));

        CancelarCU.setText("Cancelar");
        CancelarCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCUActionPerformed(evt);
            }
        });
        jPanel1.add(CancelarCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        AceptarCU.setText("Aceptar");
        AceptarCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCUActionPerformed(evt);
            }
        });
        jPanel1.add(AceptarCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        Nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre1.setText("Nombre del usuario origen:");
        jPanel1.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 40));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 270, 40));

        Nombre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre2.setText("Nombre del usuario destino:");
        jPanel1.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void AceptarCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCUActionPerformed
        Ventana1.getMiGrafo().conectarNodos(func.solicitar_usuario(jTextField1), func.solicitar_usuario(jTextField2));
        this.setVisible(false);
    }//GEN-LAST:event_AceptarCUActionPerformed

    private void CancelarCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCUActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarCUActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConectarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCU;
    private javax.swing.JButton CancelarCU;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel TituloCU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
