/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Extras.Funciones;

/**
 *
 * @author G. Angelo, S. Estefania y S. Jose
 */
public class DesconectarUsuarios extends javax.swing.JFrame {

    public Funciones func;

    /**
     * Constructor de la clase DesconectarUsuarios. Inicializa la interfaz
     * gráfica y otras funcionalidades necesarias para desconectar un usuario.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @version: 27/10/2023
     */
    public DesconectarUsuarios() {
        initComponents();
        func = new Funciones();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TituloDU = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CancelarDU = new javax.swing.JButton();
        AceptarDU = new javax.swing.JButton();
        Nombre1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloDU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloDU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloDU.setText("Desconectar Usuarios");
        jPanel2.add(TituloDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, 40));

        CancelarDU.setText("Cancelar");
        CancelarDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarDUActionPerformed(evt);
            }
        });
        jPanel2.add(CancelarDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        AceptarDU.setText("Aceptar");
        AceptarDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarDUActionPerformed(evt);
            }
        });
        jPanel2.add(AceptarDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        Nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre1.setText("Nombre del usuario origen:");
        jPanel2.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 40));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 270, 40));

        Nombre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre2.setText("Nombre del usuario destino:");
        jPanel2.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Campo de texto donde se debe colocar el usuario origen.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     * @version: 27/10/2023
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Manejador de eventos para el botón "Aceptar". Desconecta dos nodos en el
     * grafo utilizando los usuarios ingresados en los campos de texto y luego
     * oculta la ventana actual.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     */
    private void AceptarDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarDUActionPerformed
        Ventana1.getMiGrafo().desconectarNodos(func.solicitar_usuario(jTextField1), func.solicitar_usuario(jTextField2));
        this.setVisible(false);
    }//GEN-LAST:event_AceptarDUActionPerformed

    /**
     * Evento que permite cancelar la interaccion del usuario y regresar a la
     * ventana anterior.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     * @version: 27/10/2023
     */
    private void CancelarDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarDUActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarDUActionPerformed

    /**
     * Campo de texto donde se debe colocar el usuario destino.
     *
     * @author G. Angelo, S. Estefania y S. Jose
     * @param evt El evento de acción que desencadena este método.
     * @version: 27/10/2023
     */
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesconectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesconectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesconectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesconectarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesconectarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarDU;
    private javax.swing.JButton CancelarDU;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel TituloDU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
